### ISSUE TITLE
Detect a server side disconnect and handle it

### ISSUE THREAD

**Issue by amlwwalker** [jaggedsoft/node-binance-api#31] opened 2018-01-03 13:58 UTC
Hi,

Is there a way I can detect if the Binance socket goes down and call a function if so? I see there is the `reconnect:true` optional flag, but I would like to know that it went down before the reconnect is attempted (and whether the reconnect worked).
can I do anything like:

```
binance.websockets.on("disconnected"...)
```
or something?

**Comment by jaggedsoft** [comment] 2018-01-03 19:40
Hi there, `reconnect` currently defaults to true and attempts to happen seamlessly

We could make `reconnect` accept an optional callback that if present gets called before reconnecting

**Comment by jsappme** [comment] 2018-01-05 15:03
I am getting messages like this after running the websocket for a while:

`WebSocket connection closed! lskbtc@depth`

Is it normal? Is it supposed to reconnect by itself?

Is there a Telegram or Discord dedicated to the Binance API somewhere?

**Comment by jaggedsoft** [comment] 2018-01-07 21:19
Yes it will reconnect by itself automatically and your app will keep running without issues (most of the time)
There is a telegram for the binance api but you can ask questions about this library here on this github

https://t.me/binance_api_english

**Comment by jaggedsoft** [comment] 2018-01-07 21:20
I have to close this issue for now. If there is more demand I will reopen it. However, I am extremely busy with other projects at the moment

**Comment by poppahorse** [comment] 2018-01-29 22:00
@jaggedsoft having the issue also. I don't even seem to get the reconnect attempt, it just loses sync without hitting any of the reconnect [stuff here](https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L198).

It literally just loses sync, and stops receiving the data. On the [official binance socket docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md) it says connections should stay alive for 24 hours, but sometimes it seems to go after as little as 20 mins.

All the solutions I can see are for the [websockets server](https://github.com/websockets/ws#how-to-detect-and-close-broken-connections), but nothing for when you only have control of the client.

You mention [here that you have a solution for user data](https://github.com/jaggedsoft/node-binance-api/issues/9), but I am running into this on candlesticks and trades.

I appreciate you are busy, and I'd be more than happy to try and resolve and submit a PR if you can point me in the right direction :)

**Comment by jaggedsoft** [comment] 2018-01-29 23:49
Historically, websocket reconnections happened no problem - i could leave my app running for weeks and every socket would reconnect every time
there's a few things that need to be fixed/improved:

1. Websocket reconnections should continue retrying if the first attempt doesn't succeed
2. Websockets reconnections should be placed in a queue so they don't all happen at once
3. Reconnection interval should be user configurable, with the first reconnection being instantaneous, and the next 150ms after, etc. So as to not get blacklisted if 100+ sockets disconnect at once
4. `trades` and `candlesticks` websockets do not currently reconnect automatically - needs fix

I am willing to make these changes, just trying to figure out what needs to be done

**Comment by jaggedsoft** [comment] 2018-01-29 23:50
It appears what happened last night is binance disconnected everybody, and was down for a short time. Thus, the one and only reconnection attempt failed.
I believe we need a system to continue attempting reconnections periodically until successful

**Comment by kevflynn** [comment] 2018-01-31 03:02
Are other people not having this happen constantly?
I'm running: 
            ws.ping('ping');
every 20 seconds.
On each of the ws connnections and when the pong is received I store the date. 
In a watchdog loop, I look at each of the dates and if the pong date for that ticker hasn't been received in over 2 minutes, I start logging that ticker and how long it's been since the last pong was received. Without fail, within about 10 minutes I start seeing random tickers disconnect and stay disconnected. Over time, more tickers disconnect and after running for about 90 minutes, 17 tickers had disconnected. 
Am I the only one having this problem? If not, I assume it's Binance and we need a workaround, but perhaps I have some other setting that's messing with the sockets?

Running this locally BTW - on a Mac Pro running node ->       v8.9.1

**Comment by jaggedsoft** [comment] 2018-01-31 03:06
Improvement ideas
1. Store timers for each websocket, if one goes stale for a certain user-defined period we can automatically force a reconnection. No data in 60-120 seconds? Reconnect.
2. Continually attempt to reconnect websockets if the first attempt failed

**Comment by jaggedsoft** [comment] 2018-01-31 03:08
Another issue is if we have many websockets open at once, and they disconnect, it will try to reconnect all of them at the same exact time. This can cause your IP to get banned temporarily
The auto reconnect code must also be able to queue multiple reconnects so they don't all fire at once

**Comment by kevflynn** [comment] 2018-01-31 19:34
Are you open to adding more 3rd party libraries like Bluebird and Promise-Queue (https://github.com/promise-queue/promise-queue)

**Comment by jaggedsoft** [comment] 2018-01-31 19:35
Yes absolutely it just needs to be reversioned to `v0.5.0` for any breaking changes

**Comment by kevflynn** [comment] 2018-01-31 22:32
@jaggedsoft  - trying running the script below. It logs to the console anytime a ticker has missed activity of over 3 minutes.
`let watchdog = {};

// Trade history
binance.prices((error, prices) => {
	console.log('Prices =>', prices);
	const keys = Object.keys(prices);
	
	binance.websockets.trades(keys, function(trades) {
		const {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
		watchdog[symbol] = new Date().getTime();
	 });
})

function watcher() {
	setTimeout(() => {
		const keys = Object.keys(watchdog);
	console.log('RUNN SCAN ============================================');
	keys.forEach(key => {
		const time = watchdog[key];
		const diff = (new Date().getTime() - time) / (1000 * 60);
		if (diff > 3) {
			console.log(key, ' Watchdog is worried => ', diff, ' minutes');
		}
		})
		watcher();
	}, 1000 * 20)
}

watcher();`



After about 3 minutes, I see this (with more and more tickers added over time):

VENBTC  Watchdog is worried =>  3.2491166666666667  minutes
EOSBTC  Watchdog is worried =>  3.2490833333333335  minutes
RUNN SCAN ============================================
VENBTC  Watchdog is worried =>  3.5824833333333332  minutes
EOSBTC  Watchdog is worried =>  3.58245  minutes
BTSETH  Watchdog is worried =>  3.1283  minutes
MCOBTC  Watchdog is worried =>  3.245816666666667  minutes
OMGBTC  Watchdog is worried =>  3.12175  minutes
YOYOBTC  Watchdog is worried =>  3.2417333333333334  minutes
OAXBTC  Watchdog is worried =>  3.32525  minutes
XMRBTC  Watchdog is worried =>  3.234566666666667  minutes
PIVXBTC  Watchdog is worried =>  3.12805  minutes
DNTBTC  Watchdog is worried =>  3.1836166666666665  minutes
ASTETH  Watchdog is worried =>  3.1287  minutes
POEBTC  Watchdog is worried =>  3.124  minutes
WAVESETH  Watchdog is worried =>  3.0006333333333335  minutes
RUNN SCAN ============================================

**Comment by jaggedsoft** [comment] 2018-01-31 22:38
Will do thanks

**Comment by jaggedsoft** [comment] 2018-01-31 22:57
![image](https://user-images.githubusercontent.com/4283360/35652058-eabc8fba-0696-11e8-96f4-537f1e2a70d9.png)
Ran fine for a time and then started seeing some messages

![image](https://user-images.githubusercontent.com/4283360/35652074-fa0e110a-0696-11e8-84b9-9480b1500cfd.png)

After looking at these pairs however I can confirm that none of them have had trades in the last several minutes

**Comment by jaggedsoft** [comment] 2018-01-31 23:06
However, yours are happening on BTC pairs. So those likely have actual trades happening
I wish I knew what the problem was. I don't see any reason for websockets to stall out without disconnecting. But I am very intrigued as to what the cause is so we can fix it

**Comment by kevflynn** [comment] 2018-01-31 23:13
Yeah - I looked up each of them and found that a few had activity, confirming some reason for the disconnect.
I wonder if it has to do with the version of Websockets + Node I'm running locally?

Node  v8.9.1
Websockets 4.0

**Comment by jaggedsoft** [comment] 2018-01-31 23:20
my specs:
node `v8.4.0` (should be fine no matter which version)
ws @ `2.3.1`
It appears the version of `ws` that I'm using is extremely old. Perhaps there were breaking changes in `v3.2.0` or `4.0` as they made several updates over the last month. I'll do some research

**Comment by kevflynn** [comment] 2018-01-31 23:20
Likewise

**Comment by kevflynn** [comment] 2018-01-31 23:30
Just ran it again on a completely different machine and right off the bat, got this:

LTCBTC  Watchdog is worried =>  3.5305  minutes
ETHUSDT  Watchdog is worried =>  3.5677333333333334  minutes
SUBETH  Watchdog is worried =>  3.5576333333333334  minutes
XRPETH  Watchdog is worried =>  3.5305  minutes
KMDBTC  Watchdog is worried =>  3.5276  minutes
WINGSETH  Watchdog is worried =>  3.4092333333333333  minutes
ENGETH  Watchdog is worried =>  3.129016666666667  minutes
MTHETH  Watchdog is worried =>  3.259916666666667  minutes
CMTETH  Watchdog is worried =>  3.2261333333333333  minutes

LTC and ETH/USDT is definitely disconnected. Hmmmm...

**Comment by jaggedsoft** [comment] 2018-01-31 23:39
I'm doing all my trading from a $5 digitalocean VPS, has had 100% uptime thus far unless binance makes an update of some sort (this is with the older version of `ws` though)
Only problem with the cheaper VPS's is you have to increase the swap size so they don't run out of memory

I just updated to the latest `ws` and am noticing some problems
![image](https://user-images.githubusercontent.com/4283360/35653256-2335cb90-069c-11e8-9e13-a54f808a7437.png)
FUELBTC has definitely had trades recently and so has ICNBTC. The most of the others look ok

So I think there is definitely something incompatible with this library and the latest version of ws, I'm gonna have to find out what's changed and fix it. In the mean time you can try `npm install ws@2.3.1` from your project directory and see if it works any better

I have identified another problem with the test code
We are opening all the websocket connections at once. That is what, 250 symbols?
So we are making 250 connections in the same instant to binance. This will probably trigger some sort of ddos protection and you will be temporarily blocked from new connections. So it's very likely that only some of the connections are actually being made

1. Need to find out why the latest version of `ws` is incompatible, then we can fix it and update package.json to require the new version
2. Need to rework the library to slowly connect if you pass an array of symbols, something like wait 150ms before opening the next connection, etc

**Comment by jaggedsoft** [comment] 2018-01-31 23:45
I rolled back to the older ws, and it's working fine

![image](https://user-images.githubusercontent.com/4283360/35653558-c1747ee0-069d-11e8-9aed-bab990658439.png)

Have verified that none of those pairs have had trades recently
Thanks for helping to figure this out :+1:

**Comment by kevflynn** [comment] 2018-02-01 00:18
np - I can confirm I see the same thing as you (looks good) if I roll back to ws@2.3.1 - so it does look like some incompatibility with ws version.

**Comment by kevflynn** [comment] 2018-02-01 00:33
Maybe I take that back - I let it run for about 20 minutes and this is what I see now:


BNBBTC  Watchdog is worried =>  9.4114  minutes
EOSETH  Watchdog is worried =>  10.09755  minutes
OMGBTC  Watchdog is worried =>  10.267166666666666  minutes
ETHUSDT  Watchdog is worried =>  10.478216666666667  minutes
QTUMETH  Watchdog is worried =>  9.985833333333334  minutes
LSKBTC  Watchdog is worried =>  10.201566666666666  minutes
CNDETH  Watchdog is worried =>  10.108783333333333  minutes
CHATBTC  Watchdog is worried =>  9.9034  minutes
EOSBTC  Watchdog is worried =>  9.8949  minutes
WTCETH  Watchdog is worried =>  10.2674  minutes
HSRETH  Watchdog is worried =>  10.3046  minutes
WTCBTC  Watchdog is worried =>  10.267233333333333  minutes
TRXETH  Watchdog is worried =>  10.198183333333333  minutes
BTCUSDT  Watchdog is worried =>  11.578566666666667  minutes
ADABTC  Watchdog is worried =>  9.41145  minutes
CNDBNB  Watchdog is worried =>  13.55235  minutes
CNDBTC  Watchdog is worried =>  10.108733333333333  minutes
TNTBTC  Watchdog is worried =>  10.201166666666667  minutes
NEOBTC  Watchdog is worried =>  10.0997  minutes
STRATBTC  Watchdog is worried =>  10.297966666666667  minutes
IOSTBTC  Watchdog is worried =>  9.476166666666666  minutes
ENGBTC  Watchdog is worried =>  9.902033333333334  minutes
NEOETH  Watchdog is worried =>  10.305333333333333  minutes
HSRBTC  Watchdog is worried =>  9.911816666666667  minutes
SNMBTC  Watchdog is worried =>  10.1032  minutes
LTCBTC  Watchdog is worried =>  9.90865  minutes
ADAETH  Watchdog is worried =>  9.471666666666666  minutes
IOTAETH  Watchdog is worried =>  10.468483333333333  minutes
NEOUSDT  Watchdog is worried =>  10.095783333333333  minutes
STRATETH  Watchdog is worried =>  10.101766666666666  minutes
POEBTC  Watchdog is worried =>  9.911566666666667  minutes
PIVXBTC  Watchdog is worried =>  11.579716666666666  minutes
BATBTC  Watchdog is worried =>  9.985816666666667  minutes
GTOBTC  Watchdog is worried =>  10.296333333333333  minutes
LSKBNB  Watchdog is worried =>  10.111033333333333  minutes
NEBLETH  Watchdog is worried =>  10.260833333333334  minutes
NEBLBTC  Watchdog is worried =>  10.108666666666666  minutes
WABIBNB  Watchdog is worried =>  4.633516666666667  minutes
XVGBTC  Watchdog is worried =>  10.26775  minutes
LTCUSDT  Watchdog is worried =>  10.259166666666667  minutes
BQXBTC  Watchdog is worried =>  10.085866666666666  minutes
INSETH  Watchdog is worried =>  10.08465  minutes
GTOBNB  Watchdog is worried =>  19.327616666666668  minutes
BNBUSDT  Watchdog is worried =>  10.275783333333333  minutes
FUNBTC  Watchdog is worried =>  10.20395  minutes
YOYOETH  Watchdog is worried =>  4.8097  minutes
LUNETH  Watchdog is worried =>  7.0518833333333335  minutes
PIVXETH  Watchdog is worried =>  13.424566666666667  minutes
ASTBTC  Watchdog is worried =>  9.481333333333334  minutes
BCCUSDT  Watchdog is worried =>  10.259133333333333  minutes
CDTETH  Watchdog is worried =>  9.468116666666667  minutes
XLMBTC  Watchdog is worried =>  10.280883333333334  minutes
DGDBTC  Watchdog is worried =>  10.17775  minutes
LINKBTC  Watchdog is worried =>  10.262683333333333  minutes
AMBBNB  Watchdog is worried =>  3.6705666666666668  minutes
SALTETH  Watchdog is worried =>  10.174583333333333  minutes
BTGBTC  Watchdog is worried =>  10.302766666666667  minutes
BTGETH  Watchdog is worried =>  10.261983333333333  minutes
CMTETH  Watchdog is worried =>  10.25235  minutes
PPTBTC  Watchdog is worried =>  10.3034  minutes
KNCBTC  Watchdog is worried =>  10.280683333333334  minutes
XMRETH  Watchdog is worried =>  10.259183333333333  minutes
PIVXBNB  Watchdog is worried =>  18.735683333333334  minutes
POEETH  Watchdog is worried =>  9.91205  minutes
MTHETH  Watchdog is worried =>  8.2462  minutes
LENDETH  Watchdog is worried =>  10.0993  minutes
NULSBNB  Watchdog is worried =>  3.53205  minutes
DLTBTC  Watchdog is worried =>  6.2008  minutes
BTSETH  Watchdog is worried =>  9.912333333333333  minutes
RDNBTC  Watchdog is worried =>  9.423066666666667  minutes
XZCBNB  Watchdog is worried =>  17.884283333333332  minutes
BRDETH  Watchdog is worried =>  4.63185  minutes
WINGSETH  Watchdog is worried =>  13.077516666666666  minutes
STORJETH  Watchdog is worried =>  15.569583333333334  minutes
KNCETH  Watchdog is worried =>  10.301116666666667  minutes
BCCETH  Watchdog is worried =>  10.259216666666667  minutes
RLCETH  Watchdog is worried =>  10.262883333333333  minutes
BTSBNB  Watchdog is worried =>  8.671933333333333  minutes
NEBLBNB  Watchdog is worried =>  9.189666666666668  minutes
APPCETH  Watchdog is worried =>  3.2594166666666666  minutes
ADXETH  Watchdog is worried =>  16.69725  minutes
LRCETH  Watchdog is worried =>  10.262033333333333  minutes
APPCBNB  Watchdog is worried =>  3.1168  minutes
BRDBNB  Watchdog is worried =>  6.2296  minutes
NAVBNB  Watchdog is worried =>  15.77565  minutes
OAXETH  Watchdog is worried =>  10.109616666666666  minutes
AIONBNB  Watchdog is worried =>  15.281183333333333  minutes
MCOBNB  Watchdog is worried =>  11.265916666666667  minutes
BCCBNB  Watchdog is worried =>  3.4090166666666666  minutes
DLTBNB  Watchdog is worried =>  14.024333333333333  minutes
WTCBNB  Watchdog is worried =>  12.1425  minutes
CMTBNB  Watchdog is worried =>  4.299666666666667  minutes
BNTETH  Watchdog is worried =>  9.458683333333333  minutes
RLCBNB  Watchdog is worried =>  9.745883333333333  minutes
TRIGBNB  Watchdog is worried =>  9.694233333333333  minutes

**Comment by kevflynn** [comment] 2018-02-01 17:07
Hey @jaggedsoft - it looks like it's something on Binance end. What do you think about doing something like this (it works for me)
https://gist.github.com/kevflynn/862dc19484a0a3b5296b6239d85be9e1

Took the approach from the WS Docs:
https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

**Comment by jaggedsoft** [comment] 2018-02-01 21:55
Looks great, that's exactly how I want to do it, just need to integrate it into the library

**Comment by Tuitio** [comment] 2018-02-04 15:54
Maybe something like the attached patch would suffice?
[node-binance-api.js.patch.txt](https://github.com/jaggedsoft/node-binance-api/files/1692977/node-binance-api.js.patch.txt)

**Closed** 2018-02-04 17:42 UTC
Labels: feature-request, resolved
