### ISSUE TITLE
Round step not working 

### ISSUE THREAD

**Issue by MauriPastorini** [jaggedsoft/node-binance-api#313] opened 2019-01-06 00:00 UTC
Hello, when I try to do the roundStep of 0.08 ETH, the roundStep returns me 0.07999000, but binance accepts 0.08 amount, is this ok?

StepSize for ETHUSDT is 0.00001000.
```
var newAmount = binance.roundStep(0.08, "0.00001000"); // This returns 0.07999000
```

Thank you very much

**Comment by jaggedsoft** [comment] 2019-01-06 08:52
![image](https://user-images.githubusercontent.com/4283360/49916364-cd71b500-fe9a-11e8-90b6-fa125328c81f.png)
You must pass stepSize (as a string) as provided by exchangeInfo. For example `"1.00000000"`
![image](https://user-images.githubusercontent.com/4283360/49916411-fb56f980-fe9a-11e8-9f73-63a3b9a24cca.png)

**Comment by jaggedsoft** [comment] 2019-01-06 08:57
You may be doing it correctly but Binance no longer offers support to its developers unfortunately so this will not be fixed unless someone sends a pull request. Apologies.

**Comment by MauriPastorini** [comment] 2019-01-06 14:08
I am already doing that, look that on my example I send the stepSize as a String, and it doesnt return the rounding as expected.
Didnt understand that about "Binance no longer offers support to its developers". Isnt this roundStep function particular of this library? What Binance has to do with it?

**Comment by jaggedsoft** [comment] 2019-01-07 12:41
Which pair are you operating this on?
This will likely have to be fixed by someone smarter than myself. Or you can ask Binance support to show us an example calculation: https://t.me/binance_api_english
If you can get an explanation on the proper way to calculate this, I am happy to implement it.

Here is the current code if someone is up to the task:
```js
function roundStep(qty, stepSize) {
    const precision = stepSize.toString().split('.')[1].length || 0;
    return ((Math.floor(qty / stepSize) | 0) * stepSize).toFixed(precision);
}
```
![image](https://user-images.githubusercontent.com/4283360/50768508-f9593e00-1280-11e9-81b8-ac1a0b0e1f56.png)

**Comment by jaggedsoft** [comment] 2019-01-07 12:57
I am a bit confused is because of the 9 pairs I see listed with a `stepSize` of `"0.00001000"` , none of them are trading for 0.08. 
![image](https://user-images.githubusercontent.com/4283360/50769406-26f3b680-1284-11e9-903d-8da33ad7da2d.png)

**Comment by MauriPastorini** [comment] 2019-01-07 14:57
The pair is ETHUSDT, and what we are trying to accomplish is given an amount placed, it rounds to a ready for trade Binance amount.

**Comment by bmino** [comment] 2019-01-21 20:21
The calculation initially looks flawed to me. In the example @MauriPastorini presents, the value of precision is 8 which is the total number of integers to the right of the decimal place (ignoring where the 1 is). This value should instead be calculated by counting the number of integers between the decimal and the 1. The correct value of precision should be 5 in this case.

With that change, the output would be "0.07999" which is not yet correct.

The other issue is how javascript handles float values. Long story short, it's kinda crap :(

But we can get around this by doing some string splicing so long as:
1) We can always round down
2) We are dealing with quantity values with a precision less than 7 or javascript will no longer let us convert floats to strings without introducing scientific notation

```
// qty MUST have a precision of less than 7 here
let amountString = qty.toFixed(qty.length);
let decimals = Math.max(stepSize.indexOf('1') - 1, 0);
let decimalIndex = amountString.indexOf('.');
return amountString.slice(0, decimalIndex + decimals + 1);
```

I do this calculation in some of my software already and if desired, I would be happy to include a few of the edge cases and submit a PR?

**Comment by jaggedsoft** [comment] 2019-01-21 20:37
Pull requests are always welcome

**Comment by bmino** [comment] 2019-01-21 23:45
The roundStep() function currently returns a string, however the documentation claims it returns a float. Which one is correct? The float makes more sense to me

**Comment by MauriPastorini** [comment] 2019-02-04 13:17
Great! Thank you. Is this issue still open?

**Comment by jaggedsoft** [comment] 2019-02-04 13:39
I believe it still returns a smaller amount than expected:
![image](https://user-images.githubusercontent.com/4283360/52210953-b5aa2200-2888-11e9-9153-6276fe95c162.png)

I can't think of a better way to do it, (maybe using bignumber.js?) though it does a pretty good job as-is

**Comment by bmino** [comment] 2019-02-09 19:42
Running that same example locally I get the expected results. The result of `roundStep()` should return a number instead of a string as shown above. Are you sure you are running v0.9.0 with my changes included?


I tested with the following dependencies
* Node Version: 11.8.0
* node-binance-api version: 0.9.0

Code:
```
const binance = require('node-binance-api')();

const a = binance.roundStep(0.08, "0.00001000");
const b = binance.roundStep(1, "0.00001000");

console.log('a');
console.log(typeof a);
console.log(a);

console.log();

console.log('b');
console.log(typeof b);
console.log(b);
```

Output:
```
a
number
0.08

b
number
1
```

**Comment by jaggedsoft** [comment] 2019-02-09 19:50
Yeah I can confirm it's working for me, great job @bmino!
```js
function roundStep(qty, stepSize) {
    // Integers do not require rounding
    if (Number.isInteger(qty)) return qty;
    const qtyString = qty.toFixed(16);
    const desiredDecimals = Math.max(stepSize.indexOf('1') - 1, 0);
    const decimalIndex = qtyString.indexOf('.');
    return parseFloat(qtyString.slice(0, decimalIndex + desiredDecimals + 1));
}
```
![image](https://user-images.githubusercontent.com/4283360/52525605-601cad80-2cac-11e9-9ade-53bc8fe74c46.png)

**Closed by jaggedsoft** 2019-02-09 19:50 UTC
Labels: help wanted, needs-solution

**Comment by viacheslavvbogdanov** [comment] 2021-04-26 20:03
The current roundStep code does not work for this number:
roundStep(8.90785,'0.00001') returns 8.90784
It is because this line const qtyString = qty.toFixed(16); turns the number into 8.9078499999999998

I changed it to 

```
const s=qty.toString()
const qtyString = s+('0').repeat(Math.max(16-(s.length-s.indexOf('.')-1,0))
```

**Comment by bmino** [comment] 2021-04-26 22:25
I've had to revisit this issue on some other projects and now have a much more robust solution. Prolly gonna open up a new PR to fix this @viacheslavvbogdanov

**Comment by bmino** [comment] 2021-04-26 23:02
the `stepSize` input parameter is marked with a type of `float` but I don't think that is correct either? this should be a string right?

**Comment by bitcoinvsalts** [comment] 2021-09-15 16:10
I also have issues with roundStep

**Comment by vdtuan** [comment] 2022-03-16 04:17
hi, I am facing this issue, any solutions here? :)
symbol BTCUSDT, qty I get from roundstep function: 0.00091
the message i get when opening new order:  msg: 'Precision is over the maximum defined for this asset.'
